### ISSUE TITLE
主页内容在mac上部分组件缩放异常

### ISSUE THREAD

**Issue by RaysLinn** [GIS-Info/next-web#40]
分辨率为1440*800
主页中的welcome-content class和welcome-page class显示异常
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/39845869/177936859-6f13dd2b-7e2d-4b55-88f5-beafb205c420.png">
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/39845869/177936936-c42c2f73-0054-4c0a-8923-4861d16587b5.png">

**Comment by kian-zh** [comment]
现在应该没有这个问题了吧
